# Generated by Django 3.2.7 on 2021-09-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20210905_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pins',
            options={'verbose_name_plural': 'Pins'},
        ),
    ]
