# Generated by Django 3.2.7 on 2021-09-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_alter_pins_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pins',
            options={},
        ),
    ]
