# Generated by Django 3.2.7 on 2021-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_alter_pins_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pins',
            options={'verbose_name_plural': 'Pins'},
        ),
    ]
