# Generated by Django 3.2.7 on 2021-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_pins_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
