# Generated by Django 3.2.7 on 2021-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_alter_pins_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='slug',
            field=models.SlugField(),
        ),
    ]
