# Generated by Django 3.2.7 on 2021-09-07 09:07

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('pins', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('slug', models.SlugField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pins_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pins')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name_plural': 'Lists',
            },
        ),
    ]
