# Generated by Django 3.2.7 on 2021-09-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20210907_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='pins_id',
        ),
        migrations.AlterField(
            model_name='lists',
            name='thumb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lists',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
