# Generated by Django 3.2.7 on 2021-09-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20210907_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={},
        ),
    ]
