# Generated by Django 3.2.7 on 2021-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_lists_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name_plural': 'Lists'},
        ),
    ]
